{'XANFIFIEY': {'idx': 0, 'count': 1, 'dist': 3, 'min_dist': 2, 'new_idx': [5], 'dist2': 1, 'min_dist2': 1,
               'new_idx2': [0]},
 'XAINFEY': {'idx': 0, 'count': 1, 'dist': 3, 'min_dist': 2, 'new_idx': [2, 4, 5], 'dist2': 1, 'min_dist2': 1,
             'new_idx2': [0, 5]},
 'XAINFDY': {'idx': 0, 'count': 2, 'dist': 2, 'min_dist': 2, 'new_idx': [0], 'dist2': 1, 'min_dist2': 1,
             'new_idx2': [0, 2, 3]},
 'XAINFY': {'idx': 0, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [0, 2, 4, 5], 'dist2': 1, 'min_dist2': 1,
            'new_idx2': [0, 2]},
 'XAEIDY': {'idx': 0, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [0], 'dist2': 1, 'min_dist2': 1,
            'new_idx2': [0, 2]},
 'XAIFNEIFEY': {'idx': 1, 'count': 1, 'dist': 4, 'min_dist': 2, 'new_idx': [4], 'dist2': 2, 'min_dist2': 1,
                'new_idx2': [4, 6]},
 'XAFNINFENEFDY': {'idx': 1, 'count': 1, 'dist': 4, 'min_dist': 4, 'new_idx': [1, 3, 6], 'dist2': 2, 'min_dist2': 2,
                   'new_idx2': [1, 6]},
 'XAFNIFIFDY': {'idx': 1, 'count': 1, 'dist': 3, 'min_dist': 2, 'new_idx': [3, 6], 'dist2': 1, 'min_dist2': 1,
                'new_idx2': [1, 6]},
 'XAFNIFEFNIFEFEY': {'idx': 1, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [1], 'dist2': 2, 'min_dist2': 2,
                     'new_idx2': [1]},
 'XAFNIFEFIFNIFY': {'idx': 1, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [1], 'dist2': 2, 'min_dist2': 2,
                    'new_idx2': [1]},
 'XAFNIFEFIFEFDY': {'idx': 1, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [1], 'dist2': 1, 'min_dist2': 1,
                    'new_idx2': [1]},
 'XAFEIFIDY': {'idx': 2, 'count': 1, 'dist': 4, 'min_dist': 2, 'new_idx': [0, 3], 'dist2': 2, 'min_dist2': 1,
               'new_idx2': [0]},
 'XAEY': {'idx': 2, 'count': 2, 'dist': 1, 'min_dist': 1, 'new_idx': [2], 'dist2': 1, 'min_dist2': 1, 'new_idx2': [2]},
 'XANINFEFDY': {'idx': 3, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [3], 'dist2': 2, 'min_dist2': 1,
                'new_idx2': [6]},
 'XANINFIEFY': {'idx': 6, 'count': 1, 'dist': 5, 'min_dist': 4, 'new_idx': [3, 4, 5], 'dist2': 2, 'min_dist2': 2,
                'new_idx2': [3, 6]},
 'XAFNFIFEIEY': {'idx': 6, 'count': 3, 'dist': 2, 'min_dist': 2, 'new_idx': [6], 'dist2': 1, 'min_dist2': 1,
                 'new_idx2': [1, 6]},
 'XAFIEFDY': {'idx': 6, 'count': 2, 'dist': 4, 'min_dist': 1, 'new_idx': [0], 'dist2': 2, 'min_dist2': 1,
              'new_idx2': [0, 3]},
 'XAFENFEFDY': {'idx': 6, 'count': 1, 'dist': 4, 'min_dist': 3, 'new_idx': [3], 'dist2': 1, 'min_dist2': 1,
                'new_idx2': [6]},
 'XAFENFEDY': {'idx': 6, 'count': 1, 'dist': 5, 'min_dist': 2, 'new_idx': [3], 'dist2': 2, 'min_dist2': 1,
               'new_idx2': [0, 2, 3]}}
