{'XANIFNY': {'idx': 0, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [0, 4, 5], 'dist2': 1, 'min_dist2': 1,
             'new_idx2': [0, 5, 6]},
 'XAINFEY': {'idx': 0, 'count': 1, 'dist': 3, 'min_dist': 2, 'new_idx': [2, 4, 5], 'dist2': 1, 'min_dist2': 1,
             'new_idx2': [0, 5]},
 'XAFENFY': {'idx': 0, 'count': 1, 'dist': 3, 'min_dist': 2, 'new_idx': [2], 'dist2': 1, 'min_dist2': 1,
             'new_idx2': [0, 2]},
 'XAFEIFY': {'idx': 0, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [0, 2, 4, 5], 'dist2': 1, 'min_dist2': 1,
             'new_idx2': [0, 2, 4, 6]},
 'XAFEIDY': {'idx': 0, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [0, 2], 'dist2': 1, 'min_dist2': 1,
             'new_idx2': [0, 2]},
 'XAENFY': {'idx': 0, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [0, 2, 4, 5], 'dist2': 1, 'min_dist2': 1,
            'new_idx2': [0, 2]},
 'XAFNINFEFNFEFEY': {'idx': 1, 'count': 1, 'dist': 4, 'min_dist': 4, 'new_idx': [1], 'dist2': 3, 'min_dist2': 3,
                     'new_idx2': [1]},
 'XAFNIFENIFEDY': {'idx': 1, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [1, 6], 'dist2': 1, 'min_dist2': 1,
                   'new_idx2': [1]},
 'XAFNIFEFNEY': {'idx': 1, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [1, 6], 'dist2': 1, 'min_dist2': 1,
                 'new_idx2': [1, 6]},
 'XAFIFNIFEFEY': {'idx': 1, 'count': 1, 'dist': 4, 'min_dist': 3, 'new_idx': [6], 'dist2': 2, 'min_dist2': 2,
                  'new_idx2': [1]},
 'XAFEIFEFIFY': {'idx': 1, 'count': 1, 'dist': 2, 'min_dist': 2, 'new_idx': [1], 'dist2': 2, 'min_dist2': 1,
                 'new_idx2': [6]},
 'XAEIFENIFEY': {'idx': 1, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [1, 4, 6], 'dist2': 2, 'min_dist2': 1,
                 'new_idx2': [6]},
 'XAEY': {'idx': 2, 'count': 1, 'dist': 1, 'min_dist': 1, 'new_idx': [2], 'dist2': 1, 'min_dist2': 1, 'new_idx2': [2]},
 'XANINEIFEDY': {'idx': 6, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [3, 6], 'dist2': 2, 'min_dist2': 2,
                 'new_idx2': [6]},
 'XAFNINFIFEY': {'idx': 6, 'count': 2, 'dist': 2, 'min_dist': 2, 'new_idx': [1, 6], 'dist2': 1, 'min_dist2': 1,
                 'new_idx2': [6]},
 'XAFNFNFEFIFEY': {'idx': 6, 'count': 1, 'dist': 3, 'min_dist': 2, 'new_idx': [1], 'dist2': 2, 'min_dist2': 2,
                   'new_idx2': [1, 6]},
 'XAFIENIFEY': {'idx': 6, 'count': 1, 'dist': 3, 'min_dist': 2, 'new_idx': [4], 'dist2': 1, 'min_dist2': 1,
                'new_idx2': [4, 6]},
 'XAFENFIFEFEY': {'idx': 6, 'count': 1, 'dist': 3, 'min_dist': 3, 'new_idx': [6], 'dist2': 2, 'min_dist2': 2,
                  'new_idx2': [1, 6]},
 'XAFEFEY': {'idx': 6, 'count': 1, 'dist': 4, 'min_dist': 1, 'new_idx': [5], 'dist2': 2, 'min_dist2': 1,
             'new_idx2': [0, 2, 4, 5]},
 'XAEFEIFY': {'idx': 6, 'count': 1, 'dist': 4, 'min_dist': 3, 'new_idx': [0, 2, 4, 5], 'dist2': 1, 'min_dist2': 1,
              'new_idx2': [0, 6]}}
